### ISSUE TITLE
NPE in AprsOgnClient.disconnect() without network

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-client-java#1]
If I call "disconnect" without internet connection I get a NullPointerException:

java.lang.RuntimeException: Unable to start service com.meisterschueler.ognviewer.OgnService@4221a9d8 with Intent { cmp=com.meisterschueler.ognviewer/.OgnService }: java.lang.NullPointerException
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2548)
	at android.app.ActivityThread.access$1900(ActivityThread.java:140)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1324)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:4898)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:511)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
	at org.ogn.client.aprs.AprsOgnClient.disconnect(AprsOgnClient.java:382)
	at com.meisterschueler.ognviewer.OgnService.onStartCommand(OgnService.java:193)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2531)
	... 10 more

**Comment by wbuczak** [comment]
Thanks! I will look into it and fix it  ASAP!

Cheers
Wojtek

--------
sorry for typos, sent from my mobile phone

**Comment by wbuczak** [comment]
Hi,

Not easy to reproduce.  If I understand well you managed to observe it under Android, when all of a sudden you switch off the internet connection (am I right ?)  Anyway, I've improved some ifs in the disconnect() to make sure there's no call on a null object. Could you please update and tell me if that fixes the problem ?

Thanks!
Cheers
Wojtek

**Comment by Meisterschueler** [comment]
Hi Wojtek,

yes, I observed the problem under Android. I switched off the internet connection. Starting the app was no problem, but closing the app caused the NPE. With the update this failure is fixed, THANK YOU.

Cheers
Konstantin
